import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RecipeHub is one of the best chain restaurant in Mymensingh, Bangladesh",
  description: "Generated by RecipeHub with Farid Akanda",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning

    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
        <body className="bg-background text-foreground">
            <Providers>
                <Navbar />
                    {children}
                <Footer />
            </Providers>
            {/* <Navbar />
            {children}
            <Footer /> */}
            <Toaster position="top-right" />
        </body>
    </html>
  );
}

// className="min-h-full flex flex-col"